spring:
  application:
    name: osc_user_center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.80.221:3306/contribution_evaluation?stringtype=unspecified
    username: root
    password: fushenqi
  session:
    timeout: 864000000
  servlet:
    multipart:
      enabled: true # 开启配置
      max-request-size: 1024MB
      max-file-size: 10MB # 最大文件大小大文件大小
server:
  port: 8082 # 端口号
  tomcat:
    max-http-form-post-size: -1 # POST请求数据不做大小限制，以免高清头像传输失败
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑删除值
      logic-not-delete-value: 0 # 逻辑未删除值
knife4j:
  enable: true # 开启增强
  setting:
    enable-swagger-models: true     # 开启SwaggerModels自定义名称
    swagger-model-name: 模块类     # SwaggerModels自定义名称
    enable-home-custom: true      # 自定义主页内容
    home-custom-path: classpath:markdown/home.md    # 主页的Markdown文件位置
    enable-footer: false    # 关闭原始Footer
    enable-footer-custom: true     # 开启自定义Footer
    footer-custom-content: 版权所有   # 自定义Footer内容
  production: true # 是否为生产环境（生产环境会屏蔽接口文档）
api:
  key: OSC